.TH "lxi-control" "1" "9 January 2009" 

.SH "NAME" 
lxi-control \- An application for controlling LXI devices

.SH "SYNOPSIS"
.PP 
.B lxi-control 
[--ip] [--port] [--scpi] [--timeout] [--discover] [--version] [--help]

.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
.B lxi-control
command.
.PP
.B lxi-control
is an application for controlling remote LXI devices on a LAN network.

.SH "OPTIONS" 
.TP
.B \--ip=<ip>
Remote device IP.
.TP
.B \--port=<port>
Remote device port.
.TP
.B \--scpi=<command>
SCPI command to be sent.
.TP
.B \--timeout=<seconds>
Network timeout in seconds.
.TP
.B \--discover
Discover LXI devices on the hosts network subnet.
.TP
.B \--version
Display program version.
.TP
.B \--help
Display help.
.SS "Exit status:"
.TP
0
if OK,
.TP
1
if minor problems (e.g., wrong options),
.TP
2
if connection problems (e.g., Timeout or connection failed),
.TP
3
if serious trouble (e.g., system calls that normaly do not fail failed).
.SH "AUTHOR" 
.PP
.B lxi-control
is Copyright (c) 2009 DoréDevelopment.
.PP 
This manual page was written by Martin Lund <mgl@doredevelopment.dk>.
